# basic options
title: The Technological Era
author: Dharshan VY
email: vadivel.t@gmail.com
description: An informative site by an enthusiastic teen
github_username:  Dharshan2007
lang: "en"

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

# Menu

navigations:
 - {file: "index.md", title: "Home", icon: home}
 - {file: "projects.md", title: "Projects", icon: home}
 - {file: "resources.md", title: "Resources", icon: home}
 - {file: "about.md", title: "About", icon: address-card}
