# basic options
title: The Modern Era
author: Dharshan VY
email: Dharshan150907@gmail.com
description: An informative blog by an enthusiastic teen
github_username:  Dharshan2007
lang: "en"

# Build settings
markdown: kramdown
theme: minima

# Menu

navigations:
 - {file: "index.md", title: "Home", icon: home}
 - {file: "projects.md", title: "Projects", icon: home}
 - {file: "resources.md", title: "Resources", icon: home}
 - {file: "about.md", title: "About", icon: address-card}
