# basic options
title: The Technological Era
author: Dharshan VY
email: vadivel.t@gmail.com
description: An informative site by an enthusiastic teen
github_username:  Dharshan2007

# Build settings
markdown: kramdown
theme: minima
